const categories = [
  ['mahshi', 'المحاشي', 'Mahshi', 'ورق عنب ومحاشي بيتية متبلة بحب.', 'Tender homemade stuffed vegetables, seasoned with love.', '🍃', 0],
  ['chicken', 'الفراخ', 'Chicken', 'اختاري قطعتك المفضلة، والسعر حسب سعر اليوم.', 'Choose your favorite cut, priced according to the day.', '🍗', 1],
  ['meat', 'اللحوم', 'Meat', 'أطباق لحوم مطبوخة بإتقان.', 'Comforting meat dishes, carefully prepared.', '🥩', 2],
  ['trays', 'الصواني', 'Trays', 'صواني تكفي اللمة.', 'Baked trays made for sharing.', '🍲', 3],
  ['vegetable-casseroles', 'طواجن الخضار', 'Vegetable Casseroles', 'السعر شامل لكل صنف. الطاجن يحتوي على نصف كيلو لحمة حسب اختيارك (لحمة حمراء أو موزة).', 'The casserole includes 500g of meat of your choice (red meat or beef shank).', '🥘', 4],
  ['rice', 'الأرز', 'Rice', 'أرز متنوع يكمل سفرتك.', 'The perfect rice for your table.', '🍚', 5],
  ['sambousek', 'السمبوسك', 'Sambousek', 'عدد ٢٠ قطعة.', '20 pieces per order.', '🥟', 6],
  ['salads', 'السلطات', 'Salads', 'سلطات طازة تكمل كل وجبة.', 'Fresh salads to complete every meal.', '🥗', 7]
];

const products = [
  [0, 'محشي ورق عنب', 'Stuffed Grape Leaves', 'ورق عنب محشو بخليط أرز متبل بطريقة بيتية.', 'Grape leaves stuffed with a home-style seasoned rice mix.', 200, 250],
  [0, 'محشي كرنب', 'Stuffed Cabbage', 'كرنب طازج بحشوة أرز شهية.', 'Fresh cabbage rolls with a delicious rice filling.', 180, 230],
  [0, 'محشي كوسة', 'Stuffed Zucchini', 'كوسة صغيرة محشية بتتبيلة بيتية.', 'Baby zucchini filled with home-style rice.', 150, 200],
  [0, 'محشي باذنجان', 'Stuffed Eggplant', 'باذنجان محشي بطعم مصري أصيل.', 'Eggplant stuffed with authentic Egyptian flavor.', 150, 200],
  [0, 'محشي فلفل', 'Stuffed Peppers', 'فلفل ملون بحشوة غنية.', 'Colorful peppers with a rich rice filling.', 130, 180],
  [0, 'ممبار', 'Mombar', 'ممبار بلدي محشو ومتبّل.', 'Traditional stuffed sausage with herbs.', 320, 370],
  [0, 'محشي مشكل', 'Mixed Mahshi', 'تشكيلة محاشي لكل الأذواق.', 'A selection of homemade stuffed vegetables.', 150, 200],
  [1, 'فراخ مشوية', 'Grilled Chicken', 'فراخ مشوية بتتبيلة الشيف.', 'Grilled chicken with the chef’s signature marinade.', null, null],
  [1, 'فراخ بالبطاطس', 'Chicken with Potatoes', 'صينية فراخ وبطاطس بطعم البيت.', 'Home-style chicken and potato tray.', null, null],
  [1, 'شيش طاووق', 'Shish Tawook', 'قطع فراخ طرية ومتّبلة.', 'Tender marinated chicken skewers.', null, null],
  [1, 'أوراك فراخ', 'Chicken Thighs', 'أوراك فراخ متبلة وجاهزة.', 'Marinated, ready-to-cook chicken thighs.', null, null],
  [1, 'بانيه', 'Chicken Pane', 'بانيه مقرمش بتتبيلة خفيفة.', 'Crispy chicken pane with gentle seasoning.', null, null],
  [1, 'شاورما فراخ', 'Chicken Shawarma', 'شاورما فراخ بطعم مميز.', 'Flavorful homemade chicken shawarma.', null, null],
  [1, 'استربس', 'Chicken Strips', 'استربس مقرمشة للصغار والكبار.', 'Crispy strips for everyone.', null, null],
  [1, 'كوردون بلو', 'Cordon Bleu', 'كوردون بلو محشي وجاهز للتسوية.', 'Stuffed cordon bleu, ready to cook.', null, null],
  [2, 'لحمة محمرة', 'Browned Meat', 'قطع لحمة طرية بصوص غني.', 'Tender meat in a rich sauce.', null, 700],
  [2, 'لحمة بالبصل', 'Meat with Onions', 'لحمة بالبصل بطعم بيتي.', 'Home-style meat with caramelized onions.', null, 750],
  [2, 'لحمة بالبطاطس', 'Meat with Potatoes', 'صينية لحمة وبطاطس.', 'A comforting meat and potato tray.', null, 750],
  [2, 'عكاوي', 'Oxtail', 'عكاوي فاخرة بسعر اليوم.', 'Rich oxtail priced according to the day.', null, null],
  [2, 'بوفتيك', 'Beefsteak', 'بوفتيك طري ومتبّل.', 'Tender, marinated beefsteak.', 600, 650],
  [2, 'برجر', 'Burger', 'برجر بيتي غني بالنكهة.', 'Juicy homemade burger.', null, 350],
  [2, 'كفتة رز', 'Rice Kofta', 'كفتة رز مصرية أصيلة.', 'Authentic Egyptian rice kofta.', 350, null],
  [2, 'كفتة مشوية', 'Grilled Kofta', 'كفتة مشوية على أصولها.', 'Classic grilled kofta.', 400, 450],
  [3, 'مكرونة بالبشاميل', 'Béchamel Pasta', 'مكرونة بالبشاميل واللحمة المفرومة.', 'Béchamel pasta with seasoned minced meat.', 400, 450],
  [3, 'مكرونة نجرسكو', 'Negresco Pasta', 'مكرونة كريمية بالفراخ.', 'Creamy chicken Negresco pasta.', 450, 500],
  [3, 'رقاق اللحمة', 'Meat Raqaq', 'رقاق مورّق بحشوة اللحمة.', 'Layered pastry filled with meat.', 400, 450],
  [3, 'جلاش لحمة', 'Meat Goulash', 'جلاش مقرمش باللحمة.', 'Crispy goulash with meat.', 350, 400],
  [3, 'جلاش جبنة', 'Cheese Goulash', 'جلاش بالجبن الذائبة.', 'Goulash with melty cheese.', 320, 370],
  [3, 'مسقعة', 'Moussaka', 'مسقعة باذنجان بيتية.', 'Home-style eggplant moussaka.', 300, 350],
  [3, 'مسقعة باللحمة المفرومة', 'Moussaka with Meat', 'مسقعة غنية باللحمة المفرومة.', 'Rich moussaka with minced meat.', 400, 450],
  [3, 'كوسة بالبشاميل', 'Zucchini Béchamel', 'كوسة بالبشاميل والجبنة.', 'Zucchini with béchamel and cheese.', 400, 450],
  [4, 'بامية', 'Okra', 'طاجن بامية غني بالنكهة.', 'Flavorful okra casserole.', 450, 450],
  [4, 'بسلة', 'Peas', 'طاجن بسلة بيتي.', 'Home-style peas casserole.', 450, 450],
  [4, 'فاصوليا', 'Green Beans', 'طاجن فاصوليا طازجة.', 'Fresh green beans casserole.', 450, 450],
  [4, 'سبانخ', 'Spinach', 'طاجن سبانخ دافئ.', 'Warm spinach casserole.', 450, 450],
  [4, 'كوسة', 'Zucchini', 'طاجن كوسة خفيف ولذيذ.', 'Light and delicious zucchini casserole.', 450, 450],
  [5, 'أرز أبيض', 'White Rice', 'أرز أبيض مفلفل.', 'Fluffy white rice.', 150, 150],
  [5, 'أرز شعيرية', 'Vermicelli Rice', 'أرز بالشعيرية محمص.', 'Toasted vermicelli rice.', 200, 200],
  [5, 'أرز بالخلطة والمكسرات', 'Rice with Nuts', 'أرز بالخلطة والمكسرات.', 'Rice with a rich nut mix.', 300, 300],
  [5, 'أرز بسمتي سادة', 'Plain Basmati', 'أرز بسمتي مفلفل.', 'Fluffy basmati rice.', 280, 280],
  [5, 'أرز بسمتي بالمكسرات', 'Basmati with Nuts', 'بسمتي بالمكسرات.', 'Basmati rice with nuts.', 320, 320],
  [5, 'أرز بالكبد والأواص', 'Rice with Liver', 'أرز بالكبد والأواص.', 'Rice with liver and giblets.', 350, 350],
  [6, 'سمبوسك لحمة', 'Meat Sambousek', 'سمبوسك محشو باللحمة.', 'Sambousek filled with meat.', 220, 270],
  [6, 'سمبوسك لحمة بالبصل المكرمل', 'Meat & Caramelized Onion Sambousek', 'لحمة وبصل مكرمل في عجينة مقرمشة.', 'Meat and caramelized onion in crisp pastry.', 200, 250],
  [6, 'سمبوسك جبنة ونعناع', 'Cheese & Mint Sambousek', 'جبنة ونعناع منعش.', 'Cheese and refreshing mint.', 150, 200],
  [6, 'سمبوسك ميكس جبن', 'Mixed Cheese Sambousek', 'تشكيلة جبن لذيذة.', 'A delicious mixed cheese filling.', 180, 220],
  [6, 'سمبوسك شاورما فراخ', 'Chicken Shawarma Sambousek', 'شاورما فراخ في سمبوسك.', 'Chicken shawarma sambousek.', 230, 300],
  [7, 'كول سلو', 'Coleslaw', 'كول سلو كريمي وطازج.', 'Creamy, fresh coleslaw.', 250, 250],
  [7, 'خضار بالمايونيز', 'Vegetables with Mayo', 'خضار ملون بالمايونيز.', 'Colorful vegetables with mayo.', 300, 300],
  [7, 'سلطة خضراء', 'Green Salad', 'سلطة خضراء يومية.', 'Fresh green salad.', 150, 150],
  [7, 'طحينة', 'Tahini', 'طحينة ناعمة بطعم غني.', 'Smooth, rich tahini.', 100, 100],
  [7, 'سلطة فاصوليا', 'Bean Salad', 'سلطة فاصوليا منعشة.', 'Refreshing bean salad.', 200, 200],
  [7, 'بابا غنوج', 'Baba Ghanoush', 'بابا غنوج مدخن.', 'Smoky baba ghanoush.', 200, 200]
];

module.exports = { categories, products };
